resources:
- name: mocker
  type: mock

jobs:
- name: one-job
  plan:
  - get: mocker
  - task: hello
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
      run:
        path: echo
        args: ["hello"]
