image: docker:git

variables:
  DOCKER_REPOSITORY: mendersoftware/mender-convert
  IMAGE_NAME: mender-convert
  MENDER_CLIENT_VERSION: '2.0.0'

stages:
  - test
  - build

test:
  stage: test
  script:
    - apk add --no-cache bash
    - git clone git://github.com/mendersoftware/mendertesting
    # Check commit compliance.
    - mendertesting/check_commits.sh
    # Check licenses
    - mendertesting/check_license.sh

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE_NAME} --build-arg mender_client_version=${MENDER_CLIENT_VERSION} .
    - docker save $DOCKER_REPOSITORY:pr > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar

