project_name: snap-o-matic

builds:
  - binary: snap-o-matic
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64

    hooks:
      pre: make -d

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

release:
  github:
    owner: exoscale-labs
    name: snap-o-matic
  draft: true
