build:
  binary: terraform-provider-nexus_v{{ .Version }}
  env:
    - CGO_ENABLED=0 # force static builds
  goos:
  - darwin
  - linux
  - windows
  ignore:
  - goos: darwin
    goarch: 386

archives:
# Terraform expects a "v" in the plugin version identifier
- name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
