repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.3
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
        exclude: ^(tools/.*)$
      - id: go-imports
      - id: go-mod-tidy
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: go-static-check
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
