# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/jupyterhub-kubespawner/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # NOTE:    We also install the kubespawner package itself, because we use
    #          the autodoc_traits sphinx extension to generate documentation via
    #          source code inspection.
    #
    - method: pip
      path: .
