language: python
sudo: false
python:
  - nightly
  - 3.6
  - 3.5
  - 3.4

# install dependencies
install:
  - pip install -e .

# command to run tests
script:
  - python setup.py test

matrix:
  fast_finish: true
