language: minimal

# Disable git shallow clone. We need full history for validating copyright year of each file.
git:
    depth: false

dist: trusty

before_script:
    - git clone git://github.com/mendersoftware/mendertesting

script:
    # Check commit compliance.
    - mendertesting/check_commits.sh
    # Check licenses
    - mendertesting/check_license.sh
    - ./docker-build
