language: python
sudo: required
dist: xenial

# install dependencies
install:
  - pip install --upgrade setuptools pip
  - |
    if [[ ! -z "$KUBE_PY" ]]; then
      # install pinned kubernetes
      pip install -e ".[test]" "kubernetes==$KUBE_PY.*"
    else
      # add --pre so that we test with prereleases of dependencies
      # to catch compatibility issues before they enter final releases
      pip install --upgrade --pre -e ".[test]"
    fi
  - source ci/minikube.env
  - ./ci/install-kube.sh
  - pip freeze

# command to run tests
script:
  - pytest --cov kubespawner -v
after_success:
  - pip install codecov
  - codecov

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
  include:
    - python: nightly
    - python: 3.5
      env: KUBE_PY=7
    - python: 3.6
      env: KUBE_PY=7
    - python: 3.7
      env: KUBE_PY=8
