language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  include:
  - php: 7.3
    env: "CORE_BRANCH=stable17"
  - php: 7.3
    env: "CORE_BRANCH=v17.0.0"
  - php: 7.2
    env: "DB=mysql"
  - php: nightly
    env: "PATCH_VERSION_CHECK=TRUE"

env:
  global:
  - SERVER_BRANCH=master
  - DB=sqlite
  - PATCH_VERSION_CHECK=FALSE

addons:
  mariadb: '10.3'

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"

cache:
  directories:
  - "$HOME/.composer/cache/files"

before_install:
  - php --version
  - mysql --version

  # Check out the Nextcloud server via git
  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $SERVER_BRANCH
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then echo "<?php" > server/lib/versioncheck.php; fi
  - if [[ "$PATCH_VERSION_CHECK" = "TRUE" ]]; then  sed -ri 's/(<php min\-version="[0-9\.]+") max\-version="[0-9\.]+"/\1/g' twofactor_admin/appinfo/info.xml; fi

  # Move the app under test into Nextcloud's `apps` directory
  - mv twofactor_admin server/apps/

install:
  # Install the db
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database nc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'nc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON nc_autotest.* TO 'nc_autotest'@'localhost';"; fi

  # Install the server
  - php -f server/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Enable debug mode to get more info in case a test fails
  - php -f server/occ config:system:set debug --value=true --type boolean

  # Install composer dependencies
  - pushd server/apps/twofactor_admin
  - composer install
  - popd

  # Set up app
  - php -f server/occ app:enable twofactor_admin

before_script:
  # Switch bach to the app directory
  - cd server/apps/twofactor_admin

script:
  # Lint php files
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run unit/integration tests
  - ./vendor/bin/phpunit -c tests/phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml
