dist: bionic
os: linux
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
services:
  - docker
language: go
go:
  - "1.14.x"

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - make stop-services
  - make start-services

script:
  - make test
  - make vet
  - >
    NEXUS_URL=http://127.0.0.1:8081 NEXUS_USERNAME=admin NEXUS_PASSWORD=admin123
    AWS_ACCESS_KEY_ID="minioadmin" AWS_SECRET_ACCESS_KEY="minioadmin" AWS_ENDPOINT="http://minio:9000"
    make testacc
#  - make website-test

branches:
  only:
    - master
    - develop

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
