name: 'Setup Ruby, JRuby and TruffleRuby'
description: 'Download a prebuilt Ruby and add it to $PATH in 5 seconds'
author: 'Benoit Daloze'
branding:
  color: red
  icon: download
inputs:
  ruby-version:
    description: 'Engine and version to use in the format "myruby-X.Y.Z"'
    required: true
outputs:
  ruby-prefix:
    description: 'The prefix of the installed ruby'
runs:
  using: 'node12'
  main: 'dist/index.js'
