name: 'GitHub API commit'
description: 'Commits changes to your repository via the GitHub API instead of git commands'
author: 'Grafana'
inputs:
  token:
    required: true
    description: 'GitHub access token'
  stage-all-files:
    required: true
    description: 'Whether to additionally stage all changed files in the repo prior to committing'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
