version: '2.1'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        # ports:
        #     - 1009:80
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=postco.test-nictiz.nl
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=postco.test-nictiz.nl
            - LETSENCRYPT_EMAIL=mertens@nictiz.nl
            - VUE_APP_I18N_LOCALE=nl
            - VUE_APP_I18N_FALLBACK_LOCALE=en
        depends_on:
            - nodejs
        networks:
            - postco-internal
            - proxy
            
    
    nodejs:
        build:
            context: './vue'
            dockerfile: 'Dockerfile_prod'
        expose:
            - 80
        networks:
            postco-internal:
                aliases:
                    - nodejs


    templateservice:
        build: ./SnomedTemplateService
        # ports:
        #     - '9125:80'
        expose:
            - 80
        environment: 
            TEMPLSVC_EXITAFTERCHECK:
        networks:
            postco-internal:
                aliases:
                    - templateservice

networks:
    postco-internal:
        external: false
        name: postco-internal
    proxy:
        external: true
volumes:
    node_modules: