version: '2.1'
services:  
    nodejs:
        build:
            context: './vue'
            dockerfile: 'Dockerfile'
        volumes:
            - './vue:/usr/src/app'
            - 'node_modules:/usr/src/app/node_modules'
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - CORS_DEBUG=1
        ports:
            - '9124:8080'
        networks:
            postco-internal:
                aliases:
                    - nodejs
    templateservice:
        build: ./SnomedTemplateService
        ports:
            - '9125:80'
        networks:
            - postco-internal
networks:
    postco-internal:
        external: false
        name: postco-internal
volumes:
    node_modules:
