version: '3'

services:
  db:
    image: postgres
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    # command: web --conjur-appliance-url=http://localhost:3000 --conjur-account=cucumber --conjur-authn-login=admin --conjur-authn-api-key=1pg6xqd26rwwv939h7vhr2a7f5z028zpmac1k6hb5226gkgq835yz9s7 conjur-team-secret-template=/concourse/{{Team}}/{{Secret}}
    depends_on: [db]
    ports:
    - 8080:8080
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLUSTER_NAME: dev

      CONCOURSE_CONJUR_APPLIANCE_URL: http://192.168.86.198:3000
      CONCOURSE_CONJUR_ACCOUNT: cucumber
      CONCOURSE_CONJUR_AUTHN_LOGIN: admin
      CONCOURSE_CONJUR_AUTHN_API_KEY: 1pg6xqd26rwwv939h7vhr2a7f5z028zpmac1k6hb5226gkgq835yz9s7
      CONCOURSE_CONJUR_PIPELINE_SECRET_TEMPLATE: myapp/github/myProject/{{.Secret}}
      CONCOURSE_CONJUR_TEAM_SECRET_TEMPLATE: myapp/github/myProject/{{.Secret}}

  worker:
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    ports:
    - 7777:7777
    - 7788:7788
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: web:2222

      # avoid using loopbacks
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay

      # so we can reach Garden/Baggageclaim for debugging
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
