[package]
before_cmds = [
	"composer install --no-dev -o",
	"npm install --deps",
	"npm run build",
]

exclude = [
	"build",
	"composer.json",
	"composer.lock",
	"composer.phar",
	"CONTRIBUTING.md",
	"coverage",
	".git",
	".gitattributes",
	".github",
	".gitignore",
	"l10n/no-php",
	".tx",
	"Makefile",
	"node_modules",
	"package.json",
	"package-lock.json",
	"phpunit*xml",
	"screenshots",
	".scrutinizer.yml",
	"tests",
	".travis.yml",
	"vendor/bin",
]
