---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: linux-rc

outputs:
- name: fly-linux
- name: fly-windows
- name: fly-darwin

run:
  path: concourse/ci/tasks/scripts/extract-fly-assets
