---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golangci/golangci-lint}

inputs:
- name: concourse

caches:
- path: gopath
- path: old-ref

run:
  path: concourse/ci/tasks/scripts/golang-lint
