apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashlane-audit-logs.fullname" . }}
  labels:
    {{- include "dashlane-audit-logs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dashlane-audit-logs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dashlane-audit-logs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dashlane-audit-logs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: fluent-bit-conf
              mountPath: "/opt/fluent-bit.conf"
              subPath: "fluent-bit.conf"
              readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.config.env }}
          env:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command: 
                - hostname
          readinessProbe:
            exec:
              command: 
                - hostname
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fluent-bit-conf
          configMap:
            name: {{ include "dashlane-audit-logs.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
