resource_types:
  - name: time
    type: registry-image
    source:
      repository: concourse/time-resource

resources:
  - name: every-minute
    type: time
    source:
      interval: 1m

config: &config
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: busybox
  run:
    path: /bin/sh
    args:
      - -cex
      - |
        sleep 10
        echo hello world

jobs:
  - name: test-parallel
    plan:
    - get: every-minute
      trigger: true
    - in_parallel:
        limit: 3
        steps:
        - task: echo1
          config: *config
        - task: echo2
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: busybox
            run:
              path: /bin/sh
              args:
                - -cex
                - |
                  sleep 5
                  eccho
        - task: echo3
          config: *config
        - task: echo4
          config: *config
        fail_fast: true
