version: '3'
services:
  nexus-oss:
    image: "sonatype/nexus3:${NEXUS_VERSION}"
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - "${PWD}/oss-nexus.properties:/nexus-data/etc/nexus.properties"
    profiles:
      - oss
  nexus-pro:
    image: "sonatype/nexus3:${NEXUS_VERSION}"
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - "${PWD}/pro-nexus.properties:/nexus-data/etc/nexus.properties"
      - "${PWD}/license.lic:/nexus-data/etc/license.lic"
    profiles:
      - pro
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
    command: "server /data"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
