name: Test manual setup
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-18.04', 'macos-latest' ]
        ruby: [ 'ruby-2.6.5', 'ruby-2.7.0', 'truffleruby-19.3.0', 'jruby-9.2.9.0' ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo ::set-env name=HOME::$HOME
    - run: mkdir ~/.rubies
    - run: wget https://github.com/eregon/ruby-install-builder/releases/download/builds/${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
      working-directory: ${{ env.HOME }}/.rubies
    - run: tar xf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
      working-directory: ${{ env.HOME }}/.rubies
    - run: echo "::add-path::${{ env.HOME }}/.rubies/${{ matrix.ruby }}/bin"
    - run: ruby -v
    - run: ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(2014) }'
