name: npm-publish
on:
  push:
    branches:
      - "main" # Change this if not your default branch
    paths:
      - 'package.json'
      - '.github/workflows/npm-publish.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: install
        run: yarn install
      - run: (cd demo-react/app; yarn install)
      - run: (cd demo-react/iframe; yarn install)
      - run: yarn run test -- --headless
      - name: Publish package on NPM 📦
        run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
      # - uses: JS-DevTools/npm-publish@v3
      #   with:
      #     token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
      #     access: 'public'
