name: setup-taskfile workflow

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          version: 10.x

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run format-check

      - name: npm test
        run: npm test

  check-packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build

      - name: Package action
        run: npm run pack

      - name: Check packaging
        # Ignoring CR because ncc's output has a mixture of line endings, while the repository should only contain
        # Unix-style EOL.
        run: git diff --ignore-cr-at-eol --color --exit-code dist
