# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: Test

# Trigger the workflow's on pushed branches, pull requests, and manually run
# workflows.
on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    # Declare bash be used by default in this workflow's "run" steps.
    #
    # NOTE: bash will by default run with:
    #   --noprofile: Ignore ~/.profile etc.
    #   --norc:      Ignore ~/.bashrc etc.
    #   -e:          Exit directly on errors
    #   -o pipefail: Don't mask errors from a command piped into another command
    shell: bash

jobs:
  run-pytest:
    name: Run pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        #
        # k3s:                https://github.com/kubernetes/kubernetes/tags
        # k8s-python-client:  https://github.com/kubernetes-client/python#compatibility
        #
        include:
          # Test k8s-python-client 9 (k8s 1.14)
          - python: 3.6
            k8s: 1.13.12
            k8s-python-client: 9
          # Test k8s-python-client 10 (k8s 1.15)
          - python: 3.7
            k8s: 1.14.10
            k8s-python-client: 10
          # Test k8s-python-client 11 (k8s 1.15)
          - python: 3.8
            k8s: 1.15.12
            k8s-python-client: 11
          # Test k8s-python-client 12 (k8s 1.16)
          - python: 3.9
            k8s: 1.16.15
            k8s-python-client: 12
          # Try with latest k8s
          - name: latest_k8s
            python: 3.8
            k8s: 1.19.3
            k8s-python-client: 12
          # Try with JupyterHub's current state in git
          - python: 3.8
            k8s: 1.16.15
            k8s-python-client: 12
            jupyterhub: master

          # Test k8s-python-client etc. in pre-release (k8s 1.17)
          - python: 3.9
            k8s: 1.17.14
            k8s-python-client: pre

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install package and test dependencies
        env:
          K8S_PYTHON_CLIENT_VERSION: ${{ matrix.k8s-python-client }}
          JUPYTERHUB_VERSION: ${{ matrix.jupyterhub }}
        run: |
          if [[ "$K8S_PYTHON_CLIENT_VERSION" == "pre" ]]; then
              PRE="--pre"
              PINS=""
          else
              PRE=""
              PINS="kubernetes==${K8S_PYTHON_CLIENT_VERSION}"
          fi
          if [ "$JUPYTERHUB_VERSION" == "master" ]; then
              PINS="$PINS git+https://github.com/jupyterhub/jupyterhub"
          fi

          pip install --upgrade setuptools pip
          pip install -e ".[test]" ${PRE} ${PINS}
          pip freeze

      # flake8 runs a very quick code analysis without running any of the code
      # it analyses
      - name: Run flake8
        run: |
          flake8 kubespawner

      # install kubectl, minikube and start minikube
      - name: Setup k8s
        env:
          K8S_VERSION: ${{ matrix.k8s }}
        run: |
          source ci/minikube.env
          ./ci/install-kube.sh

      - name: Run pytest
        run: |
          pytest -v --cov kubespawner --color=yes

      - name: Submit a codecov report
        run: |
          pip install codecov
          codecov


  # Keep this job synced with the publish job in publish.yaml!
  package-build:
    name: Test package build
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -alh dist
