name: Test this action
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-18.04', 'macos-latest' ]
        ruby: [ 'ruby-2.6.5', 'ruby-2.7.0', 'truffleruby-19.3.0', 'jruby-9.2.9.0' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v
    - run: ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(2014) }'
