name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches-ignore:    
      - 'dependabot/**'
  pull_request_target:
    branches:
      - 'dependabot/**'

permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/new-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/new-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Flipped around
      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/non-existant.json
          base-stats-json-path: ./__tests__/__mocks__/non-existant.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Non existant
      - uses: ./
        with:
          current-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          base-stats-json-path: ./__tests__/__mocks__/old-stats-assets.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: No changes
