version: '3'

services:
  db:
    image: postgres:${TEST_POSTGRES_TAG:-latest}
    shm_size: 1gb
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: ../..
    image: ${TEST_CONCOURSE_DEV_IMAGE:-concourse/concourse:local}
    command: web
    depends_on: [db]
    ports: [8080]
    volumes: ["./keys:/concourse-keys"]
    environment:
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/session_signing_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/authorized_worker_keys
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/tsa_host_key

      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLUSTER_NAME: test

  worker:
    build: ../..
    image: ${TEST_CONCOURSE_DEV_IMAGE:-concourse/concourse:local}
    command: worker
    privileged: true
    depends_on: [web]
    stop_signal: SIGUSR2
    volumes: ["./keys:/concourse-keys"]
    environment:
      CONCOURSE_TSA_PUBLIC_KEY: /concourse-keys/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /concourse-keys/worker_key

      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: web:2222

      CONCOURSE_RUNTIME: ${TEST_CONCOURSE_RUNTIME:-guardian}

      # avoid using loopbacks
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay

      # configure a network range that doesn't overlap with the outer worker
      # when running in CI
      CONCOURSE_GARDEN_NETWORK_POOL: '10.224.0.0/16'

      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: 'true'
